- aria/data/datasets.py
- aria/data/midi.py
- aria/tokenizer/tokenizer.py
- requirements.txt
- tests/test_data.py
- tests/test_tokenizers.py
- tests/test_training.py
Made the following changes:
- Changed the file formats for MidiDataset and TokenizedDataset to jsonl
- Added the functionality for MidiDataset objects to be built directly to a file
- Refactored TokenizedDataset so that it dynamically loads sequences using mmap
- Added tests for MidiDataset and TokenizedDataset
NOTE: Training framework has not been updated to account for these changes.
> improve loading/saving for datasets

- ROADMAP.md
- aria/data/midi.py
Thie PR fixes a small bug where different channels on the same track can cause the notes from different instruments to collide in `extract_track_data`.
> Fix MidiDict extract_track_data channel bug

- ROADMAP.md
- aria/data/datasets.py
- aria/data/midi.py
This PR makes the following changes:
- Add a `calculate_hash` function to MidiDict.
- Use `calculate_hash` to automatically detect duplicates in `build_mididict_dataset`.
> Add duplicate detection to MidiDataset build process

- aria/data/datasets.py
- aria/data/midi.py
- aria/tokenizer/tokenizer.py
- tests/test_data.py
- tests/test_tokenizers.py
- Change the form that prefix tokens take. The token "piano" will now be ("prefix", "piano").
- Fix duplicate drum messages in TokenizerLazy
- Fix drum messages from being decoded over the incorrect channel (1 instead of 0).
- Make small improvements to detokenize_midi_dict in TokenizerLazy
- Fix a bug with dim_tok causing a data test to fail.
Note that as we are changing TokenizerLazy, it will no longer work with old model checkpoints.
> Change prefix token implementation - BREAKING

- aria/data/datasets.py
- aria/data/midi.py
- aria/tokenizer/tokenizer.py
- config/config.json
- tests/test_data.py
In this PR we make the following changes: 
- Add metadata to MidiDict.
- Add functionality for customising the metadata collected in midi_to_dict. 
- Add functions for parsing composer metadata from meta_msgs and the original file name.
- Refactor MidiDataset preprocessing testing by introducing midi.get_test.
> Add metadata collection to MidiDict

- ROADMAP.md
- aria/data/midi.py
- aria/tokenizer/tokenizer.py
- config/config.json
- tests/test_data.py
- tests/test_tokenizers.py
- Refactor the way that prefix tokens work for TokenizerLazy. Now they take the form `("prefix", type, data)`. 
- Add composer prefix tokens to TokenizerLazy.
- Add functionality for including composer prefix tokens in `tokenize_midi_dict` according to metadata.
> Add composer prefix tokens to TokenizerLazy

- aria/data/midi.py
- config/config.json
In this PR we make the the following changes:
- Add a preprocessing test which checks MidiDicts are over a minimum number of seconds.
> Add length preprocessing test

- ROADMAP.md
- aria/tokenizer/tokenizer.py
- tests/test_data.py
- tests/test_tokenizers.py
- Add a chord mix-up augmentation function to TokenizerLazy. This function will randomly reorder concurrent notes.
- Create a tokenizer test for checking the speed of the augmentation functions.
> Add chord mix-up augmentation function to TokenizerLazy

- ROADMAP.md
- aria/data/datasets.py
- aria/tokenizer/tokenizer.py
In this PR we fix the striding mechanism in TokenizedDataset so that it doesn't cutoff notes midway through.
> Fix striding in TokenizedDataset

- aria/data/datasets.py
- aria/data/midi.py
- Add functionality for splitting a MidiDataset into train and validation datasets.
- Refactor `midi.build_mididict_dataset` for clarity.
> Add dataset train-test splitting 

- aria/data/datasets.py
- aria/tokenizer/tokenizer.py
Fixed issue where unnecessary drum trucks were being added in `TokenizerLazy.detokenize_midi_dict`. Note that some MIDI visualization tools still display multiple drum tracks for some reason.
> Fix unnecessary drum tracks in LazyTokenizer 

- aria/train.py
- tests/test_training.py
- Introduce the function `save_model_from_cp' which converts a compiled model checkpoint to a normal one
- Add testing `save_model_from_cp'
- Increase the number of warmup steps
> Implement model saving for compiled models 

- aria/data/midi.py
- aria/train.py
Fixed a bug where MIDI files without tempo messages are not parsed correctly.
> Fix tempo bug in get_duration_ms

- aria/model/model.py
- aria/sample.py
- aria/train.py
- run.py
Small change to exclude padding tokens from contributing to loss during training/eval.
> Ignore padding loss while training

- aria/data/midi.py
- config/config.json
- Add an additional MIDI preprocessing test which calculates note frequency per present instrument
- Adjust `config.json` appropriately
> Add additional note frequency test 

- aria/data/datasets.py
- aria/data/midi.py
- config/config.json
Improve preprocessing test logging so that it displays the calculated value alongside the test results.
> Improve preprocessing test logging

- aria/model/dynamic_yarn.py
- aria/model/model.py
- aria/sample.py
> Implement kv-caching, add more variance of extrapolation (CFG) and interpolation methods

- Makefile
- aria/model/dynamic_yarn.py
- aria/model/model.py
- aria/sample.py
- config/models/large_yarn.json
- config/models/test_yarn.json
- config/models/xlarge_yarn.json
- tests/test_models.py
> Bug fix and improve YaRN

- aria/data/datasets.py
- aria/data/jsonl_zst.py
- aria/data/midi.py
- aria/model/model.py
- aria/run.py
- config/config.json
- tests/test_data.py
note: I thought we might hide some latency by doing json.decode async during tokenizer encoding. But doesn't feel like helping much....... However, I have a separate script to build a static huggingface tokenized dataset and it seems to help.
update: Now it's slightly faster by using persistent workers reading queues in `while True` loops, instead of process pool. The processes are spun up only once and therefore tokenizers are pickled only once
> MidiDataset optimizations

- aria/data/datasets.py
- aria/run.py
- aria/tokenizer/tokenizer.py
- aria/train.py
- tests/test_data.py
- tests/test_tokenizers.py
- tests/test_training.py
- Upgrade TokenizedDataset into two new classes which have the desired behaviour for pretraining and finetuning
- Fix various tokenizer bugs
> Upgrade to PretrainDataset and FinetuneDataset
